install and uninstall scripts and icon from freepik

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,18 @@
 #!/bin/zsh
 
+if [[ $EUID -ne 0 ]]; then
+    echo "This script must be run as root"
+    exit 1
+fi
+
+eva="eva"
+if ! command -v $eva &> /dev/null
+then
+    echo "eva could not be found"
+    echo "Please install eva before running this script"
+    exit 1
+fi
+
 echo "Installing the calculator onto your system..."
 
 CWD=$(pwd)
